---
- hosts: local
  remote_user: vagrant
  sudo: yes
  gather_facts: false
  tasks:
    - name: ensure apache2 is at latest version
      apt: pkg={{ item }} state=latest update_cache=true cache_valid_time=3600
      with_items:
        - apache2
        - mysql-server
        - php5
        - php5-mcrypt
        - php5-mysql
        - libapache2-mod-php5
        - libapache2-mod-auth-mysql
        - phpmyadmin

    - name: ensure that ServerName is localhost
      lineinfile: dest=/etc/apache2/conf.d/name line='ServerName localhost' create=yes state=present owner=root group=root mode=0644
      notify:
        - restart apache2

    - name: ensure apache2 is running
      service: name=apache2 state=started

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
